-- Real (non-owner) scan-report opens per client. Definer rights so it reads the
-- service-role-only scan_opens under RLS, exposing only aggregates (mirrors
-- scan_open_stats). Self-clicks already excluded by is_owner + owner_ips.
-- Join (see db/NOTES-kpi-verification.md SLUG_JOIN): there is no scan_slug column.
--   scan_opens.company_slug -> scans.company_slug -> scans.prospect_token
--   -> outreach_prospects.id -> campaign_id -> outreach_campaigns.client_id.
--
-- CHANGE from 007 (client derivation only — everything else unchanged): a skeptic
-- audit (goal-runs/sends-kpi-elevation-2026-07-24/phase1/s3-joingap-skeptic.md)
-- found the old "tokenless = ivan" default is wrong for RISE-branded reports.
-- 47 of 149 live `scans` rows carry Rise's brand block
-- (report_json->'dtc'->'brand'->>'wordmark' = 'RISE DTC') and are ALL
-- prospect_token=null (they're generated by Rise's own scan funnel, not
-- outreach, so they never get a token) — structurally invisible to the token
-- join, previously silently misattributed to 'ivan'. One of those 47,
-- neve-foods-7f (Nora Fierman, RiseDTC — Client Orbit prospect, dm_sent
-- 2026-07-22T03:20:42Z), is open-bearing: 3 non-owner opens, the first landing
-- 25 seconds after the DM went out — unambiguously Rise outreach traffic.
-- Corrected client_id = coalesce(campaign-derived client, RISE-wordmark branch,
-- 'ivan'). Campaign-derived client wins when a real prospect_token join exists
-- (the authoritative source); the wordmark branch only fires for the tokenless
-- Rise-funnel scans that have no other way to attribute. At today's data this
-- moves 3 opens (1 distinct slug) from ivan to risedtc: ivan opens_total 67->64,
-- risedtc (new row) opens_total 0->3. See s3 for the full non-owner-open audit
-- of the other 46 Rise-branded slugs (90 owner/demo opens, correctly excluded).
--
-- Most scans are still inbound with a null prospect_token and no Rise wordmark;
-- those keep defaulting to 'ivan' (the repo default-client convention).
create or replace view inbox_scan_opens_v with (security_invoker = off) as
with j as (
  select so.opened_at, so.company_slug,
         coalesce(c.client_id,
                   case when sc.wordmark = 'RISE DTC' then 'risedtc' end,
                   'ivan') as client_id
  from scan_opens so
  -- Collapse duplicate scans rows per slug (a re-scan inserts another row); the
  -- bare left join would fan out and multi-count every open for that slug.
  -- Carry the RISE DTC brand wordmark through the same dedup so the client
  -- derivation above can fall back to it when there's no campaign/token match.
  left join (
    select distinct on (company_slug) company_slug, prospect_token,
           report_json->'dtc'->'brand'->>'wordmark' as wordmark
    from scans order by company_slug, prospect_token nulls last
  ) sc on sc.company_slug = so.company_slug
  left join outreach_prospects pr on pr.id::text = sc.prospect_token
  left join outreach_campaigns  c  on c.id = pr.campaign_id
  where so.is_owner = false
)
select client_id,
  count(*) filter (where opened_at >= now() - interval '7 days')  as opens_7d,
  count(*) filter (where opened_at >= now() - interval '30 days') as opens_30d,
  count(*)                                                        as opens_total,
  count(distinct company_slug)                                    as distinct_prospects,
  max(opened_at)                                                  as last_open
from j group by client_id;

grant select on inbox_scan_opens_v to anon, authenticated;

-- Optional operator backfill (NOT auto-run): once applied, this makes the join
-- resolve neve-foods-7f -> campaign a2194be6 -> risedtc directly via the token
-- path (belt-and-suspenders with the wordmark branch above; either alone is
-- sufficient for this one row today).
-- update scans set prospect_token='bb842d9a-daa5-42fa-ad62-9336e68e704c' where company_slug='neve-foods-7f' and prospect_token is null;
